apiVersion: source.fluxcd.io/v1alpha1
kind: GitRepository
metadata:
  name: cuttlefacts-auto
spec:
  url: ssh://git@github.com/squaremo/cuttlefacts-app-automated
  interval: 1m
  secretRef:
    name: cuttlefacts-auto-deploy
